"""first table

Revision ID: bf996ddcf8ea
Revises: 
Create Date: 2021-01-30 05:56:45.354361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf996ddcf8ea'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('place', sa.String(length=200), nullable=False),
    sa.Column('timeplace', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jockeys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('age', sa.INTEGER(), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=False),
    sa.Column('rating', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('owners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=False),
    sa.Column('telephone', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('horses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('age', sa.INTEGER(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('competition_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_jockey', sa.Integer(), nullable=True),
    sa.Column('id_horse', sa.Integer(), nullable=True),
    sa.Column('id_competition', sa.Integer(), nullable=True),
    sa.Column('winner_place', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_competition'], ['competition.id'], ),
    sa.ForeignKeyConstraint(['id_horse'], ['horses.id'], ),
    sa.ForeignKeyConstraint(['id_jockey'], ['jockeys.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('competition_detail')
    op.drop_table('horses')
    op.drop_table('owners')
    op.drop_table('jockeys')
    op.drop_table('competition')
    # ### end Alembic commands ###
